language: java

jdk:
  - oraclejdk8
  
before_install: 
  - chmod +x gradlew

env:
  -
  - JCSDK=jc221
  - JCSDK=jc222
  - JCSDK=jc303
  - JCSDK=jc304
  - JCSDK=jc305u1
  
script:
  - ./gradlew check --info
  - ./gradlew buildJavaCard --info
