language: java

env:
  -
  - JCSDK=jc221
  - JCSDK=jc222
  - JCSDK=jc303
  - JCSDK=jc304
  - JCSDK=jc305u1

jdk:
  - oraclejdk8
  
before_install: 
  - chmod +x gradlew
  
script:
  - ./gradlew check --info
  - ./gradlew buildJavaCard --info

after_failure:
- ./gradlew clean check --debug
